development:
  adapter: postgresql
  encoding: unicode
  database: progress-api_development
  pool: 5
  username: benyorke
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: progress-api_test
  pool: 5
  username: benyorke
  password:

